### ISSUE TITLE
Postgres linux-static pod does not work

### ISSUE THREAD

**Issue by arichiardi** [babashka/babashka-sql-pods#32]
**0.0.5**, **babashka v0.3.1**, **linux-amd64**

**problem**

The `linux-static-amd64` does not seem to work well. I don't have an explanation and did not investigate further. What I observed is that the queries against my database where hanging.

**repro**

Sorry I don't have one. I am doing this

```clojure
(pods/load-pod (.getCanonicalPath (io/file "./lib/" "pod-babashka-postgresql")))
```

When I download the static binary in `lib`, the queries hang. All normal with `linux-amd64`.

My linux is Manjaro, an arch-like distro.

**expected behavior**

Queries should succeed.

**Comment by borkdude** [comment]
> All normal with linux-amd64

Why not just use that one? Usually it's best to use the dynamically linked one, unless it doesn't work (like in Alpine for example).

**Comment by arichiardi** [comment]
Yep of course but I wanted to report it in case someone else will stumble
into it.

**Comment by borkdude** [comment]
Thanks. I'll close the issue as I'm not sure if this requires any action and will re-open if necessary.
