### ISSUE TITLE
exception for DateTime field

### ISSUE THREAD

**Issue by mprokopov** [babashka/babashka-sql-pods#38]
babashka v0.4.1

```clojure
(require '[babashka.pods :as pods])

(pods/load-pod 'org.babashka/mysql "0.0.6")

(def db {:dbtype   "mysql"
         :host     "127.0.0.1"
         :dbname   "db"
         :user     "root"
         :password ""
         :port     3306})
(pod.babashka.mysql/execute! db ["select * from accounts;"])
```
say `accounts` table is following
```
CREATE TABLE `bots` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=445 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

In my case if table accounts contains DateTime field it throws the following exception
```
clojure.lang.ExceptionInfo: java.lang.Exception: Not supported: class java.time.LocalDateTime
```
the fields of other types look good.

**Comment by borkdude** [comment]
@mprokopov Thanks for the issue. This has to do with transit serialization, there is no default handler for `java.time.LocalDateTime` which seems to be the default type when reading a `datetime`.

**Comment by borkdude** [comment]
@mprokopov This should now be solved with the combination:

- babashka 0.4.3
- mysql pod 0.0.7

See https://github.com/babashka/pod-registry/blob/283fcc3df566af798ceb2eae43e9800466ca1eab/examples/mysql.clj#L23

**Comment by mprokopov** [comment]
@borkdude you're incredibly fast!

Work like a charm. 
Thank you!
