### ISSUE TITLE
Linux/aarch64 request

### ISSUE THREAD

**Issue by calebdiaz** [babashka/babashka-sql-pods#55]
Please it would be so great to have the possibility to connect to mysql or postgres from aarch64. Raspberry Pi of course ;)

I have this message when I try to connect "Exception in thread "main" java.lang.IllegalArgumentException: No executable found for pod org.babashka/mysql (0.1.0) and OS Linux/aarch6"

Thank you so much for this project

**Comment by lispyclouds** [comment]
I'll take a look and yes to the dynamic binary deprecation too! Do we start my making the pods lib prefer static ones only? Or this is already implemented?

**Comment by borkdude** [comment]
The pod lib doesn't care as long as it can find an executable for the OS + arch. Pods should just prefer publishing static executables which is already the case for most of the babashka pods.
